### PR TITLE
fix(app): server crash on load

### LINKED ISSUE #72: Server crashing on loading landing page!

### PR DESCRIPTION
**Pull request by MASTERCHIEF011**
Fixes #72

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ async function bootstrap() {
 
   /** configuring public and views directory */
   app.useStaticAssets(join(__dirname, '..', 'public'));
```
Comment (YashKumarVerma) [inline src/main.ts:24]: do a similar change for public as well

**Review by YashKumarVerma — APPROVED** [review]
use the following settings

```js
  app.useStaticAssets(join(__dirname, '../..', 'public'));
  app.setBaseViewsDir(join(__dirname, '../..', 'views'));
  app.setViewEngine('hbs');
```

File: src/main.ts [hunk 2]
```diff
@@ -21,8 +21,8 @@ async function bootstrap() {
   });
 
   /** configuring public and views directory */
-  app.useStaticAssets(join(__dirname, '..', 'public'));
-  app.setBaseViewsDir(join(__dirname, '..', 'views'));
+  app.useStaticAssets(join(__dirname, '../..', 'public'));
+  app.setBaseViewsDir(join(__dirname, '../..', 'views'));
   app.setViewEngine('hbs');
```
Comment (YashKumarVerma) [inline src/main.ts:26]: dope

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
brownie points for identifying and finding a neat fix.

**Comment by YashKumarVerma** [comment]
Thanks !
